### ISSUE TITLE
When using in conjunction with cypress-terminal-report, console logs are not outputted

### ISSUE THREAD

**Issue by albadam000** [YOU54F/cypress-multi-reporters#72] opened 2020-06-01 10:46 UTC
We are using cypress in conjunction with ReportPortal which is an open source test reporting and aggregation solution. We are using agent-js-cypress plugin to push the test results and logs to ReportPortal, and cypress-multi-reporters to allow generating multiple log outputs at the same time (we need agent-js-cypress for ReportPortal and mocha, mochawesome for other systems).

### Expected behavior
Expected is that regardless of the reporter used, complete output generated by cypress-terminal-reporter is shown in the output (either console or output file).

### Actual behavior
When using cypress-multi-reporters with [cypress-terminal-report](https://github.com/archfz/cypress-terminal-report), the majority of the logs are omitted. I think all the cons:log (K): calls are not shown in the output file or in the console; only the cy:command and cy:xhr calls are shown.

### Information about the Issue
The same issue is logged with cypress-terminal-report project as well: https://github.com/archfz/cypress-terminal-report/issues/28

### Steps to reproduce the behavior
When using the below configuration, most parts of the logs are missing from the report.

Cypress.json:
`  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "cypress/reporter-config.prod.json"
  }`

reporter-config.prod.json:
`{
    "reporterEnabled": "mochawesome,agent-js-cypress",
    "mochawesomeReporterOptions": {
        "reportDir": "cypress/reports/individual-reports",
        "overwrite": false,
        "html": false,
        "json": true
    },
    "reporterOptions": {
        "endpoint": "https://reportportal.xxxx/api/v1",
        "token": "xxxx",
        "launch": "xxx",
        "project": "CanaryTests",
        "description": "Synthetic monitoring tests for the main user journey including perf measurements",
        "isLaunchMergeRequired": true,
        "debug": false,
        "attributes": [
          {
            "value": "PROD"
          }
        ]
    }
}`

When using the below, all logs are present:
`  "reporter": "agent-js-cypress",
  "reporterOptions": {
    "endpoint": "https://reportportal.xxxx/api/v1",
    "token": "xxx",
    "launch": "xxx",
    "project": "CanaryTests",
    "description": "Synthetic monitoring tests for the main user journey including perf measurements",
    "isLaunchMergeRequired": true,
    "debug": false,
    "attributes": [
      {
        "value": "localDEV"
      }
    ]
  }`

**Comment by YOU54F** [comment] 2020-06-02 11:41
If you can provide a repository with a minimal example and a sample of the expected log output that would be great in investigating

**Comment by albadam000** [comment] 2020-06-09 06:32
> If you can provide a repository with a minimal example and a sample of the expected log output that would be great in investigating

Sorry for the delay, I was busy with other tasks. I tried to put together a simple example, but I can't find a consistent way to reproduce the issue.

**Comment by YOU54F** [comment] 2020-06-29 23:47
Closing due to https://github.com/archfz/cypress-terminal-report/issues/28

Please reopen with a reproducible example if this is still an issue. Many thanks!

**Closed as completed by YOU54F** 2020-06-29 23:47 UTC
