### ISSUE TITLE
Remove mocha peerDependency and add cypress as a peerDependency

### ISSUE THREAD

**Issue by crfrolik** [YOU54F/cypress-multi-reporters#54] opened 2020-04-14 19:38 UTC
### Expected behavior

Having users install mocha in their package.json is undesirable and causes problems; see also: https://github.com/cypress-io/cypress/issues/3537

Having cypress installed is sufficient, because cypress installs the version of mocha it wants.

**Comment by brettz9** [comment] 2020-04-25 05:02
If this is deemed necessary, is it the goal of the project to only be concerned with cypress support? The way the README sounds, I thought it was just a working fork off of `mocha-multi-reporters` (that happened to work with cypress also).

**Comment by brettz9** [comment] 2020-04-25 05:03
The reason I ask is because I think there should be a working fork of `mocha-multi-reporters` if this project will not work for Mocha independent of Cypress.

**Comment by hmafzal** [comment] 2020-05-04 21:48
@crfrolik looks like this should be fixed in the latest version of Cypress:
https://github.com/cypress-io/cypress/releases/tag/v4.5.0

**Comment by YOU54F** [comment] 2020-05-06 16:29
>. Having cypress installed is sufficient, because cypress installs the version of mocha it wants.

This wasn't the case until recently as Cypress shipped with a very old version of mocha, but that release is out now.

peer deps throw a warning, but don't force the user to install a version of mocha, if they don't need to. I am reluctant to add cypress as a peerDep, as @brettz9 has stated, this was intended to be a maintained fork of mocha-multi-reporters and essentially hooks into the mocha test runner and because of that, is really independent of cypress and actually applicable to users of frameworks utilising the mocha test runner.

@crfrolik I think 4.5.0 should resolve your issue, as cypress will always use the internal version of mocha, whereas that was not always the case and users who locally installed a later version of mocha (in project where they used mocha fo unit tests, and cypress for ui tests ) would have an issue where they had install mocha 6+, but cypress still used ~v2

**Comment by YOU54F** [comment] 2020-05-06 16:31
if there is an issue and we need to support separate package.json's with cypress/mocha listed independently as peer deps, then I can always support that during the release and publish 2 npm packages

**Comment by YOU54F** [comment] 2020-06-29 23:53
Closing this due to inactivity. Please re-raise if this is still an issue and what we can do to resolve in order to satisfy users of Mocha independent of cypress and cypress users

**Closed as completed by YOU54F** 2020-06-29 23:53 UTC
Labels: help wanted, question
